version: '3.8'

services:
  target_proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - app_network
    restart: always

  sqli_attacker:
    build:
      context: ./docker
      dockerfile: sqli/Dockerfile
    volumes:
      - ./docker/common:/attack/common
    networks:
      - app_network
    depends_on:
      - target_proxy
    environment:
      - TARGET_HOST=172.18.0.5
      - TARGET_PORT=80
    restart: always

  xss_attacker:
    build:
      context: ./docker
      dockerfile: xss/Dockerfile
    volumes:
      - ./docker/common:/attack/common
    networks:
      - app_network
    depends_on:
      - target_proxy
    environment:
      - TARGET_HOST=172.18.0.5
      - TARGET_PORT=80
    restart: always

  ddos_attacker:
    build:
      context: ./docker
      dockerfile: ddos/Dockerfile
    volumes:
      - ./docker/common:/attack/common
    networks:
      - app_network
    depends_on:
      - target_proxy
    environment:
      - TARGET_HOST=172.18.0.5
      - TARGET_PORT=80
    restart: always

  pathtrav_attacker:
    build:
      context: ./docker
      dockerfile: pathtrav/Dockerfile
    volumes:
      - ./docker/common:/attack/common
    networks:
      - app_network
    depends_on:
      - target_proxy
    environment:
      - TARGET_HOST=172.18.0.5
      - TARGET_PORT=80
    restart: always

networks:
  app_network:
    external: true 